/*
-- Query: Select * from demo .employees
LIMIT 0, 1000

-- Date: 2019-11-16 16:49
*/
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (1,'En','Cheng','330-972-7109','Associate Professor','Computer Science','Database Management, CS','full-time','echeng@uakron.edu','CAS 229');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (2,'Michael L.','Collard','330-972-7191','Associate Professor','Computer Science','SE, OOP, Software Evolution','full-time','collard@uakron.edu','CAS 228');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (3,'Chien-Chung','Chan','330-972-8014','Professor','Computer Science','AI, Intro to IR, Data Mining','full-time','chan@uakron.edu','CAS 227');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (4,'Willis','Crissey Renwald','330-972-8013','Assistant Professor of Instruction','Computer Science','CS, Programming for Data Scientists','full-time','wcrisseyjr@uakron.edu','CAS 239');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (5,'Zhong-Hui','Duan','330-972-6773','Professor','Computer Science','Algorithms, Bioinformatics, Advanced Algorithms','full-time','duan@uakron.edu','CAS 238');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (6,'Dianne','Foreback','330-972-7434','Assistant Professor','Computer Science','Data Structures, CS I/II','full-time','dforeback@uakron.edu','CAS 243');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (7,'Timothy W.','O Neil','330-972-6492','Professor, Department Chair','Computer Science','OS, CS, Parallel Processing','full-time','toniel@uakron.edu','CAS 221A');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (8,'Yingcai','Xiao','330-972-5809','Associate Professor','Computer Science','ISP, HCI, Computer Graphics','full-time','xiao@uakron.edu','CAS 244');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (9,'Lianghu','Tian','None','Associate Lecturer','Computer Science','CS II','part-time','ltian@uakron.edu','CAS 233');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (10,'Naman','Al-Niemi','330-972-7346','Professor of Instruction','Mathematics','Mathematics','full-time','alniemn@uakron.edu','CAS 278');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (11,'Stravroula','Androulakakis','330-972-7597','Associate Professor of Instruction','Mathematics','Calc II, Calc III','full-time','sa37@uakron.edu','CAS 247');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (12,'Curtis','Clemons','330-972-8353','Professor','Mathematics','Calc III, Differential Equations','full-time','cclemons@uakron.edu','CAS 267');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (13,'James P.','Cossey','330-972-8127','Associate Professor','Mathematics','Linear Algebra, Abstract','full-time','cossey@uakron.edu','CAS 234');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (14,'Koshal','Dahal','330-972-7400','Assistant Professor of Instruction','Mathematics','Calc I, Calc II','full-time','kdahal@uakron.edu','CAS ');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (15,'Laurie ','Dunlap','330-972-7177','Associate Professor','Mathematics','Fundamentals of Advanced Mathematics ','full-time','dunlapl@uakron.edu','CAS 264');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (16,'Diana','Eames','330-972-2097','Assistant Professor of Instruction','Mathematics','Calc II','full-time','dm73@uakron.edu','CAS 261');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (17,'Stefan','Forcey','330-972-6779','Associate Professor','Mathematics','Calc III','full-time','sf34@uakron.edu','CAS 275');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (18,'Dmitry','Golovaty','330-972-8012','Professor','Mathematics','Calc, Advanced Calculus','full-time','dmitry@uakron.edu','CAS 262');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (19,'Alexander','Hoover','330-972-7400','Assistant Professor','Mathematics','Calc I, Calc II','full-time','ahoover1@uakron.edu','CAS 252');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (20,'Brad','Justice','330-972-8352','Professor of Instruction','Mathematics','Calc I, Calc II','full-time','blj5@uakron.edu','CAS 257');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (21,'Anedra','Jones','330-972-7703','Professor of Instruction','Mathematics','Precalculus, Calc','full-time','anedraj@uakron.edu','CAS 276');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (22,'Nathan','Kilker','330-972-7199','Assistant Professor of Instruction','Mathematics',' Calc III','full-time','npk5@uakron.edu','CAS 236');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (23,'Kevin','Kreider','330-972-7519','Professor','Mathematics','Precalculus, Calc','full-time','kreider@uakron.edu','CAS 273');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (24,'Benjamin','Mackey','330-972-7400','Assistant Professor of Instruction','Mathematics','Calc I','full-time','bmackey@uakron.edu','CAS 220');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (25,'Kendall','Mauer','330-972-7514','Associate Professor of Instruction','Mathematics','Calc, Discrete Math','full-time','knm14@uakron.edu','CAS 237');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (26,'Lance','Nelson','330-972-6074','Professor of Instruction','Mathematics','Calc I, Calc II','full-time','ldn2@uakron.edu','CAS 269');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (27,'Truyen','Nguyen','330-972-2569','Associate Professor','Mathematics','Calc I, Real Analysis','full-time','tnguyen@uakron.edu','CAS 266');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (28,'Hung','Nguyen','330-972-6731','Associate Professor','Mathematics','Abstract Algebra, Theory of Numbers','full-time','hn10@uakron.edu','CAS 272');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (29,'Kimberly','Ramsey-Chin','330-972-6139','Professor of Instruction','Mathematics','Math for Everyday Life','full-time','rkimber@uakron.edu','CAS 268');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (30,'Jeffrey','Riedl','330-972-8019','Associate Professor','Mathematics','Calc I, Abstract Algebra','full-time','reidl@uakron.edu','CAS 260');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (31,'Linda','Saliga','330-972-8002','Professor','Mathematics','Fundamentals of Math for Education, Calc 2','full-time','saliga@uakron.edu','CAS 253');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (32,'Patrick','Starvaggi','330-972-7121','Assistant Professor of Instruction','Mathematics','Calc I, Calc II, Calc III','full-time','pstarvaggi@uakron.edu','CAS 274');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (33,'Ethel','Wheland','330-972-5862','Associate Professor','Mathematics','Calculus with Business','full-time','wheland@uakron.edu','CAS 263');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (34,'J. Pat','Wilber','330-972-6994','Professor','Mathematics','Complex Variables, Methods of Applied Math','full-time','jw50@uakron.edu','CAS 265');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (35,'Lingxing','Yao','330-972-7402','Assistant Professor','Mathematics','Calc I','full-time','lyao@uakron.edu','CAS 256');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (36,'Jay','Adams','330-972-7693','Associate Professor of Instruction','Electrical and Computer Engineering','DLD, Embedded Systems Scientific Computing, Simulation of Systems','full-time','jla36@uakron.edu','ASEC 458');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (37,'Malik','Elbuluk','330-972-6531','Professor','Electrical and Computer Engineering','Electric Circuits, Power Electronics, Electric Motor Drives, Electric Power Systems','full-time','melbuluk@uakron.edu','ASEC W478');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (38,'Hamid','Bahrami','330-972-7940','Associate Professor','Electrical and Computer Engineering','Digital Communications, Advanced Wireless Communications','full-time','hrb@uakron.edu','ASEC 351');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (39,'Max','Fightmaster','330-972-3608','Engineering Technician Sr. ','Electrical and Computer Engineering','-','full-time','max@uakron.edu','AERC 118B');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (40,'Joan','Carletta','330-972-7691','Professor and Associate Dean of Undergraduate','Electrical and Computer Engineering','Embedded Systems, DLD','full-time','carlett@uakron.edu','ASEC 205B');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (41,'Michael','French','330-972-6136','Associate Professor of Instruction','Electrical and Computer Engineering','Basic Electrical Engineering, Circuits I Lab, Circuits II Lab, Tools for Electrical & Computer Engineering Lecture & Lab, Embedded Systems Interfacing Lecture & Lab','full-time','mlf56@uakron.edu','ASEC South 4');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (42,'J. Alexis','De Abreu Garcia','330-972-6709','Professor','Electrical and Computer Engineering','Senior Design, Controls I/Lab, Active Circuits','full-time','alexis4@uakron.edu','ASEC 254');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (43,'James','Grover','330-972-6129','Associate Professor Emeritus','Electrical and Computer Engineering','-','full-time','jgrover@uakron.edu','-');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (44,'Virginia','Donnelly','330-972-7649','Administrative Assistant','Electrical and Computer Engineering','-','full-time','vdonnelly@uakron.edu','ASEC 156');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (45,'Subramaniya','Hariharan','330-972-6580','Professor Emeritus','Electrical and Computer Engineering','Circuits I, Circuits II','full-time','hari@uakron.edu','ASEC 454');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (400,'xxxx','xxx','3333','Docyor','CS','CS ','full-time','nwemmer1@gmail.com`','CAS 22');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (34234,'Nathan','Wemer','333333333','Doctor','CS','CS','full-time','nww8@zips.uakron.edu','CAS 111');
