/*
-- Query: select * from demo.scholarships
LIMIT 0, 1000

-- Date: 2019-11-16 14:42
*/
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (1,1,'Department of Computer Science Alumni Scholarship','Incoming Freshman','varies','The Department of Computer Science Alumni Scholarship was established in February 2003.  The scholarship is funded by contributions from departmental alumni, faculty, and friends. The Department of Computer Science Alumni Scholarship may be awarded to departmental majors and incoming freshmen who have declared a major in computer science.  The primary consideration for an award is academic performance.  Awards will be determined each year by the Department of Computer Science Scholarship Committee.  The amount of an award is dependent on the funds available and the number of students chosen to receive a Department of Computer Science Alumni Scholarship. ');
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (2,1,'Lubrizol Corporation Scholarship in Computer Science','Sophomore+, CS Major,','9000','The Lubrizol Corporation Scholarship in Computer Science is awarded annually to a deserving sophomore, junior, or senior majoring in computer science. Candidate recommendations will be made by a faculty committee within the Department of Mathematical Sciences for final approval by the Financial Aid Office. The selection will be based on the student\'s scholastic ability. The recipient also shall exhibit strong leadership qualities and good citizenship. These funds will be applied exclusively to the costs of tuition');
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (3,1,'The Marjorie J. Karlson Memorial Scholarship','3.0+, Female, Junior+','varies','The Marjorie J. Karlson Memorial Scholarship was established by her family in her memory.  Mrs. Karlson had a B.S. in Physics from Thiel College.  In the early 1950’s, she did programming on IBM computers in machine code.  She also did substitute teaching in the Orrville School System, and taught in the Head Start program for eight years. After raising five children, she returned to school and completed additional course work in Computer Sciences and Mathematics at The University of Akron.  On completion of her additional studies, Mrs. Karlson began working for The University of Akron.  She had various responsibilities in the Math and Computer Science Department for over 15 years, including Computer Science Lab Manager and Instructor of Database Management.  Mrs. Karlson had an outstanding commitment to the students.  She frequently talked of work with family and friends.  Her particular concern was that the students receive every benefit and opportunity to succeed.  ');
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (4,2,'The Ricardo Francisco Garzia Endowed Scholarship for Graduate Students in Applied Mathematics, Computer Science and Electrical Engineering','Grad Student, CS or Applied Math or EE, 3.50+','varies','The Ricardo Francisco Garzia Endowed Scholarship for Graduate Students in Applied Mathematics, Computer Science and Electrical Engineering was established in 2009 by Garzia’s family as a loving tribute to Garzia and in appreciation for the deep belief in the value of higher education he instilled in his children and grandchildren.  Ricardo Francisco Garzia was born September 19, 1926, in Buenos Aires, Argentina, where he attended college and graduate school and began a long and distinguished career as an educator, engineer and executive.  Garzia earned a BSEE from the Otto Krause School in Buenos Aires (1945), an MSEE from Universidad Nacional de La Plata Argentina (1950) and completed the coursework towards a Ph.D. in Mathematics from Universidad Nacional de La Plata Argentina (1953).In 1967 Garzia moved to the U.S. with his wife Julia Elisa Berrud de Garzia and their four children: Liliana, Silvia, Mario and Fernando.  Three of the Garzia children – Liliana, Silvia and Mario – went o');
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (5,3,'Akron Guarantee Scholarship','Incoming Freshmen, ACT/SAT dependent','Total 8000-34000','The Akron Guarantee Scholarship guarantees the annual renewal of your scholarship if you make progress toward a degree. It starts with an initial award of $1,000 to $7,500, depending on your high school GPA and ACT/SAT score. As you maintain good academic standing, the guaranteed scholarship increases in value as you earn 30, 60 and 90 credits, totalling $8,000 to $34,000 over four years. Only new, incoming freshmen are eligible for consideration');
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (6,3,'Akron Advantage Award','non-Ohio resident, 3.0+, 20+ACT or 1020+SAT','3000','If you\'re a non-Ohio resident and you have a 3.00+ GPA and 20 ACT or 1020 SAT, you may receive a $3,000 Akron Advantage Award. The Akron Advantage Award scholarship is renewable as long as you remain in good academic standing. This award will reduce your cost of tuition from $15,500 to $12,500. Only new, incoming freshmen are eligible for consideration.');
INSERT INTO `` (`scholarship_id`,`department_id`,`scholarship_name`,`requirements`,`cashAmount`,`body`) VALUES (7,3,'Akron Public Schools\' Innovation Generation Scholarship','Akron Public Schools Student','varies','In a unique partnership, the Akron Public Schools and The University of Akron will offer a scholarship opportunity to qualified APS seniors to earn a bachelor\'s degree.');
