/*
-- Query: SELECT * FROM demo.Employees
LIMIT 0, 1000

-- Date: 2019-10-29 11:52
*/
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (1,'En','Cheng','330-972-7109','Professor','Computer Science','Database Management,','full-time','echeng@uakron.edu','CAS 229');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (2,'Michael L.','Collard','330-972-7191','Associate Professor','Computer Science','SE, OOP, Software Ev','full-time','collard@uakron.edu','CAS 234');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (3,'Chien-Chung','Chan','330-972-8014','Professor','Computer Science','AI, Intro to IR, Dat','full-time','chan@uakron.edu','CAS 227');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (4,'Willis','Crissey Renwald','330-972-8013','Assistant Professor of Instruction','Computer Science','CS, Programming for ','full-time','wcrisseyjr@uakron.edu','CAS 239');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (5,'Zhong-Hui','Duan','330-972-6773','Professor','Computer Science','Algorithms, Bioinfor','full-time','duan@uakron.edu','CAS 238');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (6,'Dianne','Foreback','330-972-7434','Assistant Professor','Computer Science','Data Structures, CS','full-time','dforeback@uakron.edu','CAS 243');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (7,'Timothy W.','O Neil','330-972-6492','Professor, Department Chair','Computer Science','OS, CS, Parallel Pro','full-time','toniel@uakron.edu','CAS 221A');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (8,'Yingcai','Xiao','330-972-5809','Associate Professor','Computer Science','ISP, HCI, Computer G','full-time','xiao@uakron.edu','CAS 244');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (9,'Lianghu','Tian','None','Associate Lecturer','Computer Science','CS II','part-time','ltian@uakron.edu','CAS 233');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (10,'Naman','Al-Niemi','330-972-7346','Professor of Instruction','Mathematics','Math','full-time','alniemn@uakron.edu','CAS 278');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (11,'Stravroula','Androulakakis','330-972-7597','Associate Professor of Instruction','Mathematics','Calc','full-time','sa37@uakron.edu','CAS 247');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (12,'Curtis','Clemons','330-972-8353','Professor','Mathematics','Calc, Differential E','full-time','cclemons@uakron.edu','CAS 267');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (13,'James P.','Cossey','330-972-8127','Associate Professor','Mathematics','Linear Algebra, Abst','full-time','cossey@uakron.edu','CAS 234');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (14,'Koshal','Dahal','330-972-7400','Assistant Professor of Instruction','Mathematics','Calc','full-time','kdahal@uakron.edu','CAS ');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (15,'Laurie ','Dunlap','330-972-7177','Associate Professor','Mathematics','Fundamentals of Adva','full-time','dunlapl@uakron.edu','CAS 264');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (16,'Diana','Eames','330-972-2097','Assistant Professor of Instruction','Mathematics','Calc','full-time','dm73@uakron.edu','CAS 261');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (17,'Stefan','Forcey','330-972-6779','Associate Professor','Mathematics','Calc 3','full-time','sf34@uakron.edu','CAS 275');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (18,'Dmitry','Golovaty','330-972-8012','Professor','Mathematics','Calc, Advanced Calc','full-time','dmitry@uakron.edu','CAS 262');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (19,'Alexander','Hoover','330-972-7400','Assistant Professor','Mathematics','Calc','full-time','ahoover1@uakron.edu','CAS 252');
INSERT INTO `` (`employee_id`,`first_name`,`last_name`,`phone_number`,`title`,`department`,`teaches`,`type_of_employment`,`email`,`office_number`) VALUES (20,'Brad','Justice','330-972-8352','Professor of Instruction','Mathematics','Calc I, Calc II','full-time','blj5@uakron.edu','CAS 257');
